version: "3.9"

services:
  ml-core:
    build:
      context: .
      dockerfile: Dockerfile.ml-core
    container_name: blast-ml-core
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DESCRIPTIONS_DIR: /app/descriptions
      PINS_DIR: /app/pins
      WORK_DIR: /app/work
      OUTPUT_DIR: /app/output
    volumes:
      - ./descriptions:/app/descriptions:ro
      # pins как кеш S3 внутри контейнера
      - ./work:/app/work
      - ./output:/app/output

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile.orchestrator
    container_name: blast-orchestrator
    env_file:
      - .env
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    ports:
      - "8000:8000"

  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: blast-tg-bot
    env_file:
      - .env
    depends_on:
      - orchestrator
