services:
  finance-bot:
    build: .
    container_name: finance-bot
    environment:
      FINANCE_BOT_TOKEN: ${FINANCE_BOT_TOKEN:-8782530243:AAEodzMW1H_Y4C49WwyVc04C0poy5JaoeX4}
      GROK_API_KEY: ${GROK_API_KEY:-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}
      OWNER_TG_ID: ${OWNER_TG_ID:-975769043}
      DB_PATH: /app/data/finance.db
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:18082:8080"
    restart: unless-stopped
