"""Postgres-backed footage ASSET registry — the durable pool source of truth.

Companion to footage_tags_db (tags). Where footage_tags answers "what does this
clip look like", footage_assets answers "which clips exist, where in S3, and with
what dims". Together, keyed by clip_id, they are the ONE queryable place for the
pool:

    pickable pool = footage_assets JOIN footage_tags USING (clip_id)

Why Postgres and not just the JSON index: the JSON index is a render-hot-path
cache that is regenerated by activation and (correctly) git-ignored, so it does
NOT survive as a queryable record. footage_assets is the durable registry that
survives deploys and gives asset_ui / health ONE canonical count instead of a
funnel across S3-listing vs index vs inventory.

Ground truth is still S3; a scan (build_static_assets_index) discovers the pool
and upserts it here (storing the REAL s3_key, so downstream never has to
reconstruct a key from prefix+genre+tag). A scan for a source REPLACES that
source's rows (upsert + prune) so the registry mirrors current S3 state.

Dedup key = clip_id (the 8+ digit id embedded in the file name), same identity
as footage_tags so the join is exact. This module separates PURE transforms
(testable without a DB) from the thin asyncpg I/O layer.
"""
from __future__ import annotations

from typing import Any, Dict, Iterable, List, Optional

from mlcore.footage_tags_db import SOURCE_PHOTO, SOURCE_VIDEO, extract_clip_id

SCHEMA = """
CREATE TABLE IF NOT EXISTS footage_assets (
    clip_id       TEXT PRIMARY KEY,
    s3_key        TEXT      NOT NULL DEFAULT '',
    file_name     TEXT      NOT NULL DEFAULT '',
    genre         TEXT      NOT NULL DEFAULT '',
    tag           TEXT      NOT NULL DEFAULT '',
    src_w         INTEGER   NOT NULL DEFAULT 0,
    src_h         INTEGER   NOT NULL DEFAULT 0,
    duration_sec  DOUBLE PRECISION NOT NULL DEFAULT 0,
    dominant_color TEXT     NOT NULL DEFAULT '',
    source        TEXT      NOT NULL DEFAULT 'video',
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_footage_assets_source ON footage_assets(source);
CREATE INDEX IF NOT EXISTS idx_footage_assets_updated ON footage_assets(updated_at);
"""


# --------------------------------------------------------------------------- #
# Pure helpers (no DB)
# --------------------------------------------------------------------------- #
def _s(v: Any) -> str:
    return str(v or "").strip()


def _int(v: Any) -> int:
    try:
        return int(v or 0)
    except Exception:
        return 0


def _float(v: Any) -> float:
    try:
        return float(v or 0.0)
    except Exception:
        return 0.0


def build_asset_record(raw: Dict[str, Any], *, source: str = SOURCE_VIDEO) -> Optional[Dict[str, Any]]:
    """Map one static-index asset row -> a footage_assets record.

    Keys off the clip_id embedded in s3_key / file_name. Returns None when no
    clip_id can be extracted (cannot be keyed / joined to tags).
    """
    if not isinstance(raw, dict):
        return None
    file_name = _s(raw.get("file_name"))
    s3_key = _s(raw.get("s3_key"))
    clip_id = extract_clip_id(s3_key) or extract_clip_id(file_name)
    if not clip_id:
        return None
    dom = raw.get("dominant_color")
    return {
        "clip_id": clip_id,
        "s3_key": s3_key,
        "file_name": file_name,
        "genre": _s(raw.get("genre")),
        "tag": _s(raw.get("tag")),
        "src_w": _int(raw.get("src_w")),
        "src_h": _int(raw.get("src_h")),
        "duration_sec": _float(raw.get("duration_sec")),
        "dominant_color": _s(dom),
        "source": _s(source) or SOURCE_VIDEO,
    }


def records_from_index(assets: Iterable[Dict[str, Any]], *, source: str = SOURCE_VIDEO) -> List[Dict[str, Any]]:
    """Map static-index assets -> records, deduped by clip_id (last wins),
    dropping rows without a clip_id."""
    out: Dict[str, Dict[str, Any]] = {}
    for a in assets or []:
        rec = build_asset_record(a, source=source)
        if rec:
            out[rec["clip_id"]] = rec
    return list(out.values())


def index_row_from_record(rec: Dict[str, Any]) -> Dict[str, Any]:
    """A footage_assets row -> the static-index asset shape the picker consumes."""
    return {
        "file_name": rec.get("file_name") or "",
        "genre": rec.get("genre") or "",
        "tag": rec.get("tag") or "",
        "src_w": _int(rec.get("src_w")),
        "src_h": _int(rec.get("src_h")),
        "duration_sec": _float(rec.get("duration_sec")),
        "dominant_color": (rec.get("dominant_color") or None) or None,
        "s3_key": rec.get("s3_key") or "",
    }


# --------------------------------------------------------------------------- #
# Thin asyncpg I/O layer
# --------------------------------------------------------------------------- #
async def init_schema(conn: Any) -> None:
    await conn.execute(SCHEMA)


async def upsert_assets(conn: Any, records: List[Dict[str, Any]]) -> int:
    """Upsert asset records (ON CONFLICT clip_id). Returns number written."""
    rows = [
        (
            r["clip_id"],
            r.get("s3_key", ""),
            r.get("file_name", ""),
            r.get("genre", ""),
            r.get("tag", ""),
            _int(r.get("src_w")),
            _int(r.get("src_h")),
            _float(r.get("duration_sec")),
            r.get("dominant_color", "") or "",
            r.get("source", SOURCE_VIDEO) or SOURCE_VIDEO,
        )
        for r in (records or [])
        if r.get("clip_id")
    ]
    if not rows:
        return 0
    await conn.executemany(
        """
        INSERT INTO footage_assets
            (clip_id, s3_key, file_name, genre, tag, src_w, src_h,
             duration_sec, dominant_color, source, updated_at)
        VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10, NOW())
        ON CONFLICT (clip_id) DO UPDATE SET
            s3_key         = EXCLUDED.s3_key,
            file_name      = EXCLUDED.file_name,
            genre          = EXCLUDED.genre,
            tag            = EXCLUDED.tag,
            src_w          = EXCLUDED.src_w,
            src_h          = EXCLUDED.src_h,
            duration_sec   = EXCLUDED.duration_sec,
            dominant_color = EXCLUDED.dominant_color,
            source         = EXCLUDED.source,
            updated_at     = NOW()
        """,
        rows,
    )
    return len(rows)


async def prune_missing(conn: Any, *, source: str, keep_clip_ids: Iterable[str]) -> int:
    """Delete rows for `source` whose clip_id is NOT in keep_clip_ids (clips no
    longer present in the current S3 scan). Returns number deleted."""
    keep = [str(c) for c in keep_clip_ids if str(c or "").strip()]
    if keep:
        res = await conn.execute(
            "DELETE FROM footage_assets WHERE source = $1 AND NOT (clip_id = ANY($2::text[]))",
            source, keep,
        )
    else:
        res = await conn.execute("DELETE FROM footage_assets WHERE source = $1", source)
    # asyncpg returns e.g. "DELETE 12"
    try:
        return int(str(res).split()[-1])
    except Exception:
        return 0


async def replace_source_assets(conn: Any, records: List[Dict[str, Any]], *, source: str) -> Dict[str, int]:
    """Upsert this scan's assets and prune stale ones, so the registry mirrors
    the current S3 state for `source`. Returns {written, pruned, total}."""
    await init_schema(conn)
    written = await upsert_assets(conn, records)
    pruned = await prune_missing(conn, source=source, keep_clip_ids=[r["clip_id"] for r in records if r.get("clip_id")])
    total = await count_assets(conn, source=source)
    return {"written": written, "pruned": pruned, "total": total}


async def count_assets(conn: Any, *, source: Optional[str] = None) -> int:
    if source:
        return int(await conn.fetchval("SELECT COUNT(*) FROM footage_assets WHERE source = $1", source) or 0)
    return int(await conn.fetchval("SELECT COUNT(*) FROM footage_assets") or 0)


async def count_pickable(conn: Any, *, source: str = SOURCE_VIDEO) -> int:
    """Clips that are BOTH in the pool AND carry tags — the real pickable pool."""
    return int(await conn.fetchval(
        """
        SELECT COUNT(*)
        FROM footage_assets a
        JOIN footage_tags t ON t.clip_id = a.clip_id
        WHERE a.source = $1
          AND t.source = $1
          AND array_length(t.theme_tags, 1) > 0
        """,
        source,
    ) or 0)


async def fetch_all_assets(conn: Any, *, source: Optional[str] = None) -> List[Dict[str, Any]]:
    cols = "clip_id, s3_key, file_name, genre, tag, src_w, src_h, duration_sec, dominant_color, source"
    if source:
        recs = await conn.fetch(f"SELECT {cols} FROM footage_assets WHERE source = $1", source)
    else:
        recs = await conn.fetch(f"SELECT {cols} FROM footage_assets")
    return [dict(r) for r in recs]


async def pool_health(conn: Any, *, source: str = SOURCE_VIDEO) -> Dict[str, int]:
    """One canonical snapshot of the pool: registry size, tagged, pickable."""
    await init_schema(conn)
    total = await count_assets(conn, source=source)
    pickable = await count_pickable(conn, source=source)
    return {"assets": total, "pickable": pickable, "untagged": max(0, total - pickable)}
