services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "${DOZZLE_BIND_HOST:-0.0.0.0}:${DOZZLE_PORT:-18080}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./dozzle_data:/data
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_AUTH_TTL: 168h
