ALIGNMENT_ALGORITHM_VERSION = "local-ctc-viterbi-v4-demucs-4.1.0"

ERROR_UNSUPPORTED_TEXT = "ALIGNMENT_UNSUPPORTED_TEXT"
ERROR_WINDOW_MISMATCH = "ALIGNMENT_WINDOW_MISMATCH"
ERROR_MODEL_UNAVAILABLE = "ALIGNMENT_MODEL_UNAVAILABLE"
ERROR_SEPARATOR_UNAVAILABLE = "ALIGNMENT_SEPARATOR_UNAVAILABLE"
ERROR_SOURCE_SEPARATION_FAILED = "ALIGNMENT_SOURCE_SEPARATION_FAILED"
ERROR_TIMEOUT = "ALIGNMENT_TIMEOUT"
ERROR_INTERNAL = "ALIGNMENT_INTERNAL_ERROR"
