ALIGNMENT_ALGORITHM_VERSION = "local-ctc-viterbi-v1"

ERROR_UNSUPPORTED_TEXT = "ALIGNMENT_UNSUPPORTED_TEXT"
ERROR_WINDOW_MISMATCH = "ALIGNMENT_WINDOW_MISMATCH"
ERROR_MODEL_UNAVAILABLE = "ALIGNMENT_MODEL_UNAVAILABLE"
ERROR_TIMEOUT = "ALIGNMENT_TIMEOUT"
ERROR_INTERNAL = "ALIGNMENT_INTERNAL_ERROR"
