/*** crystal glow — generated from dump + manual S_Glint values ***/
var CONFIG = { targetCompName:null, placeRef:"Текст", startTime:null, duration:null, place:"below:Текст" };
var SILENT = true;
if (typeof $!=="undefined" && $.global && $.global.__BLAST){ var __p=$.global.__BLAST; for (var __k in __p){ if (__p[__k]!=null) CONFIG[__k]=__p[__k]; } }
function log(m){ if(SILENT){try{$.writeln(m);}catch(e){}}else alert(m); }
function findLayer(c,n){ for(var i=1;i<=c.numLayers;i++) if(c.layer(i).name===n) return c.layer(i); return null; }
function findComp(){ var a=app.project.activeItem,i,it; if(CONFIG.targetCompName){for(i=1;i<=app.project.numItems;i++){it=app.project.item(i);if(it instanceof CompItem&&it.name===CONFIG.targetCompName)return it;}} if(CONFIG.placeRef){for(i=1;i<=app.project.numItems;i++){it=app.project.item(i);if(it instanceof CompItem&&findLayer(it,CONFIG.placeRef))return it;}} if(a&&a instanceof CompItem)return a; return null; }
function place(comp,L){ var ref=findLayer(comp,CONFIG.placeRef); if(ref)try{L.moveAfter(ref);}catch(e){} var t=(CONFIG.startTime!=null)?CONFIG.startTime:0; L.startTime=0; L.inPoint=t; L.outPoint=(CONFIG.duration!=null)?Math.min(comp.duration,t+CONFIG.duration):comp.duration; }
function setP(e,n,v){ try{var p=e.property(n);if(p)p.setValue(v);}catch(x){} }
function setAny(e,names,v){for(var i=0;i<names.length;i++){try{var p=e.property(names[i]);if(p){p.setValue(v);return true;}}catch(x){}}return false;}
(function(){ if(!app.project){return;} var comp=findComp(); if(!comp){throw new Error("crystal_glow: target comp not found");} app.beginUndoGroup("crystal glow"); try{ var L=comp.layers.addSolid([1,1,1],"crystal glow",comp.width,comp.height,1); L.adjustmentLayer=true; var fx=L.property("ADBE Effect Parade"); var sh=fx.addProperty("ADBE Sharpen"); setP(sh,"ADBE Sharpen-0001",50); var gb=fx.addProperty("ADBE Gaussian Blur 2"); setP(gb,"ADBE Gaussian Blur 2-0001",2); var gl=fx.addProperty("S_Glint"); if(!gl)throw new Error("crystal_glow: Sapphire S_Glint unavailable"); setAny(gl,["S_Glint-0050","Brightness"],0.8); setAny(gl,["Hue Shift"],0); setAny(gl,["S_Glint-0056","Threshold"],0.4); setAny(gl,["Threshold Add Color"],[0,0,0,1]); setAny(gl,["S_Glint-0058","Threshold Blur"],0); setAny(gl,["S_Glint-0059","Size"],240); setAny(gl,["Blur Glint"],0); setAny(gl,["S_Glint-0067","Affect Alpha"],0.98); setAny(gl,["Glint From Alpha"],0); setAny(gl,["Glint Under Source"],0); setAny(gl,["Source Opacity"],1); setAny(gl,["Bg Brightness"],1); setAny(gl,["Invert Matte"],0); setAny(gl,["Matte Type"],1); setAny(gl,["Expand Borders"],0); setAny(gl,["Opacity"],1); place(comp,L); log("crystal glow -> "+comp.name); }finally{app.endUndoGroup();} })();
