/*** night vision — generated from adjustment + shape layer dumps ***/
var CONFIG = { targetCompName:null, placeRef:"Текст", startTime:null, duration:null, place:"below:Текст" };
var SILENT = true;
if (typeof $!=="undefined" && $.global && $.global.__BLAST){ var __p=$.global.__BLAST; for (var __k in __p){ if (__p[__k]!=null) CONFIG[__k]=__p[__k]; } }
function log(m){ if(SILENT){try{$.writeln(m);}catch(e){}}else alert(m); }
function findLayer(c,n){ for(var i=1;i<=c.numLayers;i++) if(c.layer(i).name===n) return c.layer(i); return null; }
function findComp(){ var a=app.project.activeItem,i,it; if(CONFIG.targetCompName){for(i=1;i<=app.project.numItems;i++){it=app.project.item(i);if(it instanceof CompItem&&it.name===CONFIG.targetCompName)return it;}} if(CONFIG.placeRef){for(i=1;i<=app.project.numItems;i++){it=app.project.item(i);if(it instanceof CompItem&&findLayer(it,CONFIG.placeRef))return it;}} if(a&&a instanceof CompItem)return a; return null; }
function place(comp,L){ var ref=findLayer(comp,CONFIG.placeRef); if(ref)try{L.moveAfter(ref);}catch(e){} var t=(CONFIG.startTime!=null)?CONFIG.startTime:0; L.startTime=0; L.inPoint=t; L.outPoint=(CONFIG.duration!=null)?Math.min(comp.duration,t+CONFIG.duration):comp.duration; }
function setP(e,n,v){ try{var p=e.property(n);if(p)p.setValue(v);}catch(x){} }
(function(){ if(!app.project){return;} var comp=findComp(); if(!comp){throw new Error("night_vision: target comp not found");} app.beginUndoGroup("night vision"); try{ var A=comp.layers.addSolid([1,1,1],"night vision grade",comp.width,comp.height,1); A.adjustmentLayer=true; var fx=A.property("ADBE Effect Parade"); var n=fx.addProperty("ADBE Noise2"); setP(n,"ADBE Noise2-0001",15); setP(n,"ADBE Noise2-0002",0); var u=fx.addProperty("ADBE Unsharp Mask2"); setP(u,"ADBE Unsharp Mask2-0001",400); setP(u,"ADBE Unsharp Mask2-0002",3); var m=fx.addProperty("ADBE Mosaic"); setP(m,"ADBE Mosaic-0001",500); setP(m,"ADBE Mosaic-0002",500); var g=fx.addProperty("ADBE Gaussian Blur 2"); setP(g,"ADBE Gaussian Blur 2-0001",5); var tr=fx.addProperty("ADBE Geometry2"); setP(tr,"ADBE Geometry2-0011",0); setP(tr,"ADBE Geometry2-0004",115); place(comp,A); var S=comp.layers.addShape(); S.name="night vision green"; var root=S.property("ADBE Root Vectors Group"); var grp=root.addProperty("ADBE Vector Group"); grp.name="Rectangle 1"; var c=grp.property("ADBE Vectors Group"); var rect=c.addProperty("ADBE Vector Shape - Rect"); rect.property("ADBE Vector Rect Size").setValue([comp.width,comp.height]); var fill=c.addProperty("ADBE Vector Graphic - Fill"); fill.property("ADBE Vector Fill Color").setValue([0,1,0.0235294342,1]); grp.property("ADBE Vector Transform Group").property("ADBE Vector Group Opacity").setValue(30); try{S.blendingMode=BlendingMode.ADD;}catch(e){} S.property("ADBE Transform Group").property("ADBE Position").setValue([comp.width/2,comp.height/2]); place(comp,S); log("night vision -> "+comp.name); }finally{app.endUndoGroup();} })();
