"""F4 «Движение» motion-hook overlays.

Engagement-bait AE overlays (swipe / tap / pinch / hold-finger / head-nod) that
build tension for a few seconds and resolve at the audio drop with a flash.

Each device is a self-contained injectable JSX block that builds its layers on
top of the main render comp. The block is generated by `build_overlay_jsx` and
spliced into `templates/project_template.j2` (after addFlashOnCuts, before the
project save), mirroring the existing flash-on-cuts overlay pattern.

Alignment contract:
  The bot reframes the clip window so that clip_start == hook - LEAD_BY_DEVICE.
  Since the main comp's t=0 maps to clip_start, the overlay's "cover" layers run
  from comp-time 0 and their end (== LEAD_BY_DEVICE) lands exactly on the hook.
  No in-comp time shift is required.
"""

from mlcore.hooks.f4_motion.overlay import (
    LEAD_BY_DEVICE,
    F4_DEVICES,
    build_overlay_jsx,
)

__all__ = ["LEAD_BY_DEVICE", "F4_DEVICES", "build_overlay_jsx"]
